name: Deploy to Firebase Hosting on PR

on: pull_request

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build_and_preview:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Checkout code once

      # Setup Node.js environment without caching pnpm initially
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "21" # Specify the Node.js version

      # Install pnpm
      - name: Install pnpm
        run: |
          npm install -g pnpm
          echo "$(pnpm bin)" >> $GITHUB_PATH

      # Enable pnpm caching now that pnpm is installed
      - name: Enable pnpm caching
        uses: actions/setup-node@v3
        with:
          node-version: "21"
          cache: "pnpm"

      # Check pnpm version to ensure it's installed
      - name: Check pnpm version
        run: pnpm --version

      # Install dependencies using pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # Build the project using pnpm
      - name: Build the project
        run: pnpm run build

      # Deploy to Firebase using the pre-configured GitHub Action
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_QWORDLY_699C2 }}
          projectId: qwordly-699c2

      # Notify Slack
      - name: Notify Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_CHANNEL: "releases"
          SLACK_COLOR: "#36a64f"
          SLACK_MESSAGE: "Deployment complete! Ad deployed to: https://qwordly-699c2.firebaseapp.com/ \n Give it a test here: https://p.applov.in/playablePreview?create=1&qr=1"
          SLACK_TITLE: "Qwordly Ad Deployment successful"
